version: "3.9" 
services:
  webapp1:
    image: image_image
    container_name: webapp_8090
    ports:
      - "8090:8080"
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    networks:
      - app-network

  webapp2:
    image: image_image
    container_name: webapp_8030
    ports:
      - "8030:8080"
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

version: '3.8'

services:
  hospital-app:
    build: .
    container_name: hospital-mgmt-system
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - hospital-network


  mongodb:
    image: mongo:6.0
    container_name: hospital-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: hospital_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - hospital-network



volumes:
  mongodb_data:
    driver: local

networks:
  hospital-network:
    driver: bridge



version: '3.8'

services:
  hospital-app:
    build: .
    container_name: hospital-mgmt-system
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - hospital-network

  postgresql:
    image: postgres:15
    container_name: hospital-postgresql
    restart: unless-stopped
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - hospital-network

volumes:
  postgresql_data:
    driver: local

networks:
  hospital-network:
    driver: bridge







version: "3.9"
services:
  app:
    image: myprojectimage
    container_name: myproject_app
    ports:
      - "9090:8080"   # HostPort:ContainerPort, App accessible at http://localhost:9090
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: myproject_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"   # Optional, only if you want to connect from host

volumes:
  db_data:
